source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'require_all'
gem 'sinatra'
    gem 'activerecord', :require => 'active_record'
    gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
    gem 'rake'
    gem 'require_all'
    gem 'sqlite3'
    gem 'thin'
    gem 'shotgun'
    gem 'pry'
    
group :test do
      gem 'rspec'
      gem 'capybara'
      gem 'rack-test'
      gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
    end